DROP TABLE IF EXISTS "feature_plan";
DROP TABLE IF EXISTS "features";
DROP TABLE IF EXISTS "plans";
DROP TABLE IF EXISTS "tenants";
DROP TABLE IF EXISTS "admin_permission_role";
DROP TABLE IF EXISTS "admin_role_user";
DROP TABLE IF EXISTS "admin_permissions";
DROP TABLE IF EXISTS "admin_roles";
DROP TABLE IF EXISTS "admin_users";